package com.vntana.core.model.user.role.error;

import com.vntana.commons.api.model.response.ErrorResponseModel;

/**
 * Created by Arman Gevorgyan.
 * Date: 5/12/20
 * Time: 11:28 AM
 */
public enum UserRoleErrorResponseModel implements ErrorResponseModel {
    MISSING_ORGANIZATION_UUID,
    MISSING_USER_UUID,
    MISSING_REQUESTED_USER_UUID,
    MISSING_CLIENT_ORGANIZATION_UUID,
    MISSING_CLIENT_ROLE,
    MISSING_ORGANIZATION_ROLE,
    ORGANIZATION_NOT_FOUND,
    CLIENT_ORGANIZATION_NOT_FOUND,
    INCORRECT_PERMISSION_GRANT_CLIENT_ROLE,
    INCORRECT_PERMISSION_GRANT_ORGANIZATION_ROLE,
    USER_NOT_FOUND,
    REVOCABLE_USER_HAS_ORGANIZATION_ROLE,
    REVOCABLE_USER_DOES_NOT_HAVE_CLIENT_ROLE,
    REQUESTED_ROLE_IS_ABSENT,
    REQUESTED_ROLE_ALREADY_GRANTED,
    REQUEST_ROLE_IS_NOT_CLIENT_RELATED,
    REQUESTED_USER_IS_ORGANIZATION_OWNER,
    REQUESTED_USER_ALREADY_HAS_ORGANIZATION_ADMIN_ROLE
}
